/** Auto-generated by scripts/sync-an-act-tokens.ts — do not edit */
export const TOKENS_PAYLOAD = {
  "version": "an-act-design-system-v1",
  "generated_at": "2026-06-30T03:07:15.856Z",
  "source": "src/design-system/tokens/design-tokens.ts",
  "colors": {
    "semanticGroups": [
      "background",
      "surface",
      "text",
      "accent",
      "border",
      "status",
      "interactive",
      "overlay",
      "transition"
    ],
    "semanticPaths": [
      "background.primary",
      "background.secondary",
      "background.tertiary",
      "background.inverse",
      "surface.primary",
      "surface.secondary",
      "surface.elevated",
      "surface.muted",
      "text.primary",
      "text.secondary",
      "text.tertiary",
      "text.inverse",
      "text.disabled",
      "accent.primary",
      "accent.secondary",
      "accent.highlight",
      "border.default",
      "border.subtle",
      "border.focus",
      "status.success",
      "status.warning",
      "status.error",
      "status.info",
      "interactive.default",
      "interactive.hover",
      "interactive.pressed",
      "interactive.disabled",
      "overlay.scrim",
      "overlay.backdrop",
      "transition.start",
      "transition.mid",
      "transition.end"
    ],
    "themes": {
      "need": {
        "background.primary": "#FFFFFF",
        "background.secondary": "#FAFAFA",
        "background.tertiary": "#F5F5F5",
        "background.inverse": "#000000",
        "surface.primary": "#FFFFFF",
        "surface.secondary": "#F3F4F6",
        "surface.elevated": "#FFFFFF",
        "surface.muted": "#E5E7EB",
        "text.primary": "#000000",
        "text.secondary": "#374151",
        "text.tertiary": "#6B7280",
        "text.inverse": "#FFFFFF",
        "text.disabled": "#9CA3AF",
        "accent.primary": "#2563EB",
        "accent.secondary": "#3B82F6",
        "accent.highlight": "#1D4ED8",
        "border.default": "#E5E7EB",
        "border.subtle": "#F3F4F6",
        "border.focus": "#2563EB",
        "status.success": "#059669",
        "status.warning": "#D97706",
        "status.error": "#DC2626",
        "status.info": "#2563EB",
        "interactive.default": "#2563EB",
        "interactive.hover": "#1D4ED8",
        "interactive.pressed": "#1E40AF",
        "interactive.disabled": "#93C5FD",
        "overlay.scrim": "rgba(0, 0, 0, 0.4)",
        "overlay.backdrop": "rgba(255, 255, 255, 0.8)",
        "transition.start": "#FFFFFF",
        "transition.mid": "#6B7280",
        "transition.end": "#000000"
      },
      "action": {
        "background.primary": "#000000",
        "background.secondary": "#0A0A0A",
        "background.tertiary": "#111111",
        "background.inverse": "#FFFFFF",
        "surface.primary": "#111111",
        "surface.secondary": "#1A1A1A",
        "surface.elevated": "#1F1F1F",
        "surface.muted": "#262626",
        "text.primary": "#FFFFFF",
        "text.secondary": "#D1D5DB",
        "text.tertiary": "#9CA3AF",
        "text.inverse": "#000000",
        "text.disabled": "#6B7280",
        "accent.primary": "#3B82F6",
        "accent.secondary": "#60A5FA",
        "accent.highlight": "#2563EB",
        "border.default": "#262626",
        "border.subtle": "#1A1A1A",
        "border.focus": "#3B82F6",
        "status.success": "#34D399",
        "status.warning": "#FBBF24",
        "status.error": "#F87171",
        "status.info": "#60A5FA",
        "interactive.default": "#3B82F6",
        "interactive.hover": "#60A5FA",
        "interactive.pressed": "#2563EB",
        "interactive.disabled": "#1E3A5F",
        "overlay.scrim": "rgba(0, 0, 0, 0.72)",
        "overlay.backdrop": "rgba(0, 0, 0, 0.88)",
        "transition.start": "#000000",
        "transition.mid": "#6B7280",
        "transition.end": "#FFFFFF"
      }
    }
  },
  "typography": {
    "fontFamily": {
      "sans": "\"Inter\", \"SF Pro Text\", system-ui, -apple-system, sans-serif",
      "mono": "\"SF Mono\", \"Menlo\", \"Consolas\", monospace"
    },
    "styles": {
      "display": {
        "fontFamily": "\"Inter\", \"SF Pro Display\", system-ui, -apple-system, sans-serif",
        "fontSize": "40px",
        "fontWeight": 700,
        "lineHeight": "48px",
        "letterSpacing": "-0.5px"
      },
      "heading": {
        "fontFamily": "\"Inter\", \"SF Pro Display\", system-ui, -apple-system, sans-serif",
        "fontSize": "28px",
        "fontWeight": 600,
        "lineHeight": "36px",
        "letterSpacing": "-0.25px"
      },
      "title": {
        "fontFamily": "\"Inter\", \"SF Pro Text\", system-ui, -apple-system, sans-serif",
        "fontSize": "20px",
        "fontWeight": 600,
        "lineHeight": "28px"
      },
      "body": {
        "fontFamily": "\"Inter\", \"SF Pro Text\", system-ui, -apple-system, sans-serif",
        "fontSize": "16px",
        "fontWeight": 400,
        "lineHeight": "24px"
      },
      "caption": {
        "fontFamily": "\"Inter\", \"SF Pro Text\", system-ui, -apple-system, sans-serif",
        "fontSize": "13px",
        "fontWeight": 400,
        "lineHeight": "18px",
        "letterSpacing": "0.1px"
      },
      "label": {
        "fontFamily": "\"Inter\", \"SF Pro Text\", system-ui, -apple-system, sans-serif",
        "fontSize": "12px",
        "fontWeight": 500,
        "lineHeight": "16px",
        "letterSpacing": "0.4px"
      },
      "terminal": {
        "fontFamily": "\"SF Mono\", \"Menlo\", \"Consolas\", monospace",
        "fontSize": "18px",
        "fontWeight": 400,
        "lineHeight": "24px",
        "letterSpacing": "0.2px"
      }
    }
  },
  "spacing": {
    "space-4": "4px",
    "space-8": "8px",
    "space-12": "12px",
    "space-16": "16px",
    "space-20": "20px",
    "space-24": "24px",
    "space-32": "32px",
    "space-40": "40px",
    "space-48": "48px",
    "space-64": "64px"
  },
  "radius": {
    "small": 4,
    "medium": 8,
    "large": 12,
    "extraLarge": 16,
    "pill": 9999,
    "circle": "50%"
  },
  "elevation": {
    "none": {
      "level": "none",
      "zIndex": 0,
      "shadowToken": "shadow-none"
    },
    "low": {
      "level": "low",
      "zIndex": 1,
      "shadowToken": "shadow-low"
    },
    "medium": {
      "level": "medium",
      "zIndex": 4,
      "shadowToken": "shadow-medium"
    },
    "high": {
      "level": "high",
      "zIndex": 8,
      "shadowToken": "shadow-high"
    },
    "highest": {
      "level": "highest",
      "zIndex": 16,
      "shadowToken": "shadow-highest"
    }
  },
  "shadows": {
    "shadow-none": {
      "offsetX": 0,
      "offsetY": 0,
      "blur": 0,
      "spread": 0,
      "color": "transparent"
    },
    "shadow-low": {
      "offsetX": 0,
      "offsetY": 1,
      "blur": 2,
      "spread": 0,
      "color": "rgba(0, 0, 0, 0.06)"
    },
    "shadow-medium": {
      "offsetX": 0,
      "offsetY": 4,
      "blur": 8,
      "spread": -2,
      "color": "rgba(0, 0, 0, 0.08)"
    },
    "shadow-high": {
      "offsetX": 0,
      "offsetY": 8,
      "blur": 16,
      "spread": -4,
      "color": "rgba(0, 0, 0, 0.12)"
    },
    "shadow-highest": {
      "offsetX": 0,
      "offsetY": 16,
      "blur": 32,
      "spread": -8,
      "color": "rgba(0, 0, 0, 0.16)"
    }
  },
  "motion": {
    "durations": {
      "fast": 120,
      "normal": 240,
      "slow": 400,
      "extraSlow": 640
    },
    "easing": {
      "standard": "cubic-bezier(0.4, 0, 0.2, 1)",
      "decelerate": "cubic-bezier(0, 0, 0.2, 1)",
      "accelerate": "cubic-bezier(0.4, 0, 1, 1)",
      "emphasized": "cubic-bezier(0.2, 0, 0, 1)"
    },
    "tokens": {
      "fast": {
        "durationMs": 120,
        "easing": "cubic-bezier(0.4, 0, 0.2, 1)"
      },
      "normal": {
        "durationMs": 240,
        "easing": "cubic-bezier(0.4, 0, 0.2, 1)"
      },
      "slow": {
        "durationMs": 400,
        "easing": "cubic-bezier(0, 0, 0.2, 1)"
      },
      "extraSlow": {
        "durationMs": 640,
        "easing": "cubic-bezier(0.2, 0, 0, 1)"
      }
    }
  },
  "transitions": {
    "needMode": "need",
    "transitionScreen": "transition",
    "actionMode": "action",
    "forward": {
      "direction": "need-to-action",
      "brandLine": "an act...",
      "statusLine": "Preparing...",
      "typographyStyle": "terminal",
      "durationMs": 640,
      "easing": "cubic-bezier(0.2, 0, 0, 1)",
      "backgroundSteps": [
        {
          "progress": 0,
          "colorToken": "transition.start"
        },
        {
          "progress": 0.5,
          "colorToken": "transition.mid"
        },
        {
          "progress": 1,
          "colorToken": "transition.end"
        }
      ],
      "progressBar": {
        "enabled": true,
        "height": 4,
        "trackColorToken": "surface.muted",
        "fillColorToken": "accent.primary",
        "radiusToken": "pill"
      }
    },
    "reverse": {
      "direction": "action-to-need",
      "brandLine": "an act...",
      "statusLine": "Preparing...",
      "typographyStyle": "terminal",
      "durationMs": 640,
      "easing": "cubic-bezier(0, 0, 0.2, 1)",
      "backgroundSteps": [
        {
          "progress": 0,
          "colorToken": "transition.start"
        },
        {
          "progress": 0.5,
          "colorToken": "transition.mid"
        },
        {
          "progress": 1,
          "colorToken": "transition.end"
        }
      ],
      "progressBar": {
        "enabled": true,
        "height": 4,
        "trackColorToken": "surface.muted",
        "fillColorToken": "accent.highlight",
        "radiusToken": "pill"
      }
    }
  },
  "accessibility": {
    "minimumTouchTargetPx": 44,
    "minimumContrastRatioNormalText": 4.5,
    "minimumContrastRatioLargeText": 3,
    "focusRingWidthPx": 2,
    "focusRingOffsetPx": 2,
    "keyboardNavigationRequired": true,
    "reducedMotionRespected": true
  }
} as const;
