export {
  API_AUDIT_ROUTES,
  PUBLIC_ROUTE_PREFIXES,
  ROLE_PROTECTED_PREFIXES,
  SENSITIVE_ROUTE_PREFIXES,
  buildApiAuditCenter,
  buildApiAuditSnapshot,
  buildApiDocumentationAudit,
  buildApiOverview,
  buildApiProductionReadiness,
  buildApiRecommendations,
  buildApiRiskRegister,
  buildAuthenticationAudit,
  buildEndpointCoverageAudit,
  buildModuleExposureAudit,
  buildParsedRouteRegistry,
  buildRouteRegistryAudit,
  collectApiAuditPaths,
  computeApiSurfaceScore,
  toApiAuditCenterView,
  toApiDocumentationAuditView,
  toApiOverviewView,
  toApiProductionReadinessView,
  toApiRecommendationsView,
  toApiRiskRegisterView,
  toApiSurfaceScoreView,
  toAuthenticationAuditView,
  toEndpointCoverageAuditView,
  toModuleExposureAuditView,
  toRouteRegistryAuditView,
  type ApiAuditCenter,
  type ApiAuditCenterView,
  type ApiAuditRawSnapshot,
  type ApiAuditSnapshot,
  type ApiAuditSources,
  type ApiDocumentationAudit,
  type ApiDocumentationAuditView,
  type ApiOverview,
  type ApiOverviewView,
  type ApiProductionReadiness,
  type ApiProductionReadinessView,
  type ApiRecommendations,
  type ApiRecommendationsView,
  type ApiRiskRegister,
  type ApiRiskRegisterView,
  type ApiSurfaceScore,
  type ApiSurfaceScoreView,
  type AuthenticationAudit,
  type AuthenticationAuditView,
  type EndpointCoverageAudit,
  type EndpointCoverageAuditView,
  type ModuleExposureAudit,
  type ModuleExposureAuditView,
  type RouteRegistryAudit,
  type RouteRegistryAuditView,
} from "./domain/api-audit.js";
export {
  ApiAuditService,
  createApiAuditModule,
  createApiAuditService,
  type ApiAuditModule,
} from "./application/api-audit-service.js";
export {
  ApiAuditRepository,
  createApiAuditRepository,
  apiAuditRepository,
} from "./infrastructure/api-audit-repository.js";
