export const FINANCIAL_EXPERIENCE_MODULE = "financial-experience" as const;
export {
  type EscrowInitiationStatus,
  type FundingInstructions,
  type EscrowSummary,
  type EscrowInitiationView,
  DEFAULT_EXPERIENCE_CURRENCY,
  EXPERIENCE_PLATFORM_FEE_RATE,
  isEligibleContractForEscrowInitiation,
  majorUnitsToMinor,
  readCurrencyCode,
  readContractValueMinor,
  projectPlatformFeeMinor,
  buildFundingReferenceNumber,
  buildProtectedAmountExplanation,
  buildPlatformFeeExplanation,
  buildEscrowSummary,
  buildFundingInstructions,
  buildEscrowInitiationView,
} from "./escrow-initiation.js";
