import { randomUUID } from "node:crypto";
import Fastify from "fastify";
import cookie from "@fastify/cookie";
import { resolveFastifyLogger, type Logger } from "../shared/logging/index.js";
import type { AppConfig } from "../shared/config/index.js";
import type { DbPool } from "../shared/db/index.js";
import type { IdempotencyService } from "../platform/idempotency/index.js";
import type { AuthService } from "../identity/application/auth-service.js";
import type { RegistrationService } from "../identity/application/auth-service.js";
import type { ProfileService } from "../identity/application/profile-service.js";
import type { VerificationService } from "../identity/application/verification-service.js";
import type { IdentityRevalidationService } from "../identity/application/revalidation-service.js";
import type { JwtService } from "../identity/infrastructure/jwt-service.js";
import type { SessionStore } from "../identity/infrastructure/session-store.js";
import { requestIdMiddleware, errorHandler } from "./middleware/request.js";
import {
  createIdempotencyPreHandler,
  createIdempotencyOnSend,
} from "./middleware/idempotency.js";
import { createAuthenticateMiddleware } from "./middleware/authenticate.js";
import { requireAuthMiddleware } from "./middleware/require-auth.js";
import { registerHealthRoutes } from "./routes/health.js";
import { registerAuthRoutes } from "./routes/auth.js";
import { registerSecurityAuthRoutes } from "./routes/security-auth.js";
import type { SecurityAuthKernelService } from "../security/auth-kernel-service.js";
import type { OwnershipRegistry } from "../security/ownership-registry.js";
import type { SecurityAuditService } from "../security/audit-service.js";
import { registerIdentityRoutes } from "./routes/identity.js";
import { registerVerificationRoutes } from "./routes/verification.js";
import type { ActionService } from "../action/application/action-service.js";
import type { ContractEngineService } from "../contract/application/contract-engine.service.js";
import type { ExecutionService } from "../execution/application/execution-service.js";
import type { EvaluationService } from "../execution/application/evaluation-service.js";
import type { IssueService } from "../complaint/application/issue-service.js";
import type { ActionIntelligenceService } from "../action/intelligence/action-intelligence-service.js";
import type { RequirementIntelligenceService } from "../action/intelligence/requirement/requirement-intelligence-service.js";
import type { ContractIntelligenceService } from "../contract/intelligence/contract-intelligence-service.js";
import type { TrustIntelligenceService } from "../trust/intelligence/trust-intelligence-service.js";
import type { MatchingIntelligenceService } from "../matching/intelligence/matching-intelligence-service.js";
import type { PricingIntelligenceService } from "../pricing/intelligence/pricing-intelligence-service.js";
import type { NegotiationIntelligenceService } from "../negotiation/intelligence/negotiation-intelligence-service.js";
import type { WorkflowIntelligenceService } from "../orchestrator/intelligence/workflow-intelligence-service.js";
import type { ProviderIntelligenceService } from "../provider/intelligence/provider-intelligence-service.js";
import type { ExperienceServices } from "../experience/index.js";
import { registerEscrowExperienceRoutes } from "./routes/escrow.js";
import { registerExecutionExperienceRoutes } from "./routes/execution.js";
import { registerEvidenceReadRoutes } from "./routes/evidence-read.js";
import { registerDisputesReadRoutes } from "./routes/disputes-read.js";
import type { TrustScoreService } from "../trust/application/trust-score-service.js";
import type { ProviderProfileService } from "../provider-experience/application/provider-profile-service.js";
import type { RequestIntelligenceService } from "../request-experience/application/request-intelligence-service.js";
import type { MatchContractConversionService } from "../conversion/application/match-contract-conversion-service.js";
import type { CustomerDashboardService } from "../customer-experience/application/customer-dashboard-service.js";
import type { ProviderDashboardService } from "../provider-workspace/application/provider-dashboard-service.js";
import type { AdminConsoleService } from "../operations/application/admin-console-service.js";
import type { EventInboxService } from "../notifications/application/event-inbox-service.js";
import type { DiscoveryService } from "../discovery/application/discovery-service.js";
import type { PlatformAnalyticsService } from "../analytics/application/platform-analytics-service.js";
import type { HomeExperienceService } from "../experience/application/home-experience-service.js";
import type { LiveFrameExperienceService } from "../experience/live-frame/application/live-frame-experience-service.js";
import type { ContractJourneyService } from "../experience/contract-journey/application/contract-journey-service.js";
import type { ActionEconomyService } from "../experience/action-economy/application/action-economy-service.js";
import type { RequestMatchExperienceService } from "../experience/request-match/application/request-match-experience-service.js";
import type { EscrowPaymentExperienceService } from "../experience/escrow-payment/application/escrow-payment-experience-service.js";
import type { TrustReputationExperienceService } from "../experience/trust-reputation/application/trust-reputation-experience-service.js";
import type { DiscoveryMatchingService } from "../experience/discovery-matching/application/discovery-matching-service.js";
import type { ProfessionalPassportService } from "../experience/professional-passport/application/professional-passport-service.js";
import type { ProfessionalSealsService } from "../experience/professional-seals/application/professional-seals-service.js";
import type { LiveTrustFrameService } from "../experience/live-trust-frame/application/live-trust-frame-service.js";
import type { ProviderCommandCenterService } from "../experience/provider-command-center/application/provider-command-center-service.js";
import type { CustomerCommandCenterService } from "../experience/customer-command-center/application/customer-command-center-service.js";
import type { PlatformControlTowerService } from "../experience/platform-control-tower/application/platform-control-tower-service.js";
import type { ReleaseReadinessCenterService } from "../experience/release-readiness/application/release-readiness-service.js";
import { registerTrustExperienceRoutes, registerTrustReputationRoutes } from "./routes/trust.js";
import { registerProviderRoutes } from "./routes/providers.js";
import { registerRequestRoutes } from "./routes/requests.js";
import { registerConversionRoutes } from "./routes/conversions.js";
import { registerCustomerDashboardRoutes } from "./routes/customer-dashboard.js";
import { registerProviderDashboardRoutes } from "./routes/provider-dashboard.js";
import { registerAdminConsoleRoutes } from "./routes/admin-console.js";
import { registerNotificationRoutes } from "./routes/notifications.js";
import { registerDiscoveryRoutes } from "./routes/discovery.js";
import { registerAnalyticsRoutes } from "./routes/analytics.js";
import { registerHomeRoutes } from "./routes/home.js";
import { registerLiveFrameRoutes } from "./routes/live-frame.js";
import { registerContractJourneyRoutes } from "./routes/contract-journey.js";
import { registerActionEconomyRoutes } from "./routes/action-economy.js";
import { registerRequestMatchRoutes } from "./routes/request-match.js";
import { registerEscrowPaymentRoutes } from "./routes/escrow-payment.js";
import { registerTrustReputationExperienceRoutes } from "./routes/trust-reputation.js";
import { registerDiscoveryMatchingRoutes } from "./routes/discovery-matching.js";
import { registerProfessionalPassportRoutes } from "./routes/professional-passport.js";
import { registerProfessionalSealsRoutes } from "./routes/professional-seals.js";
import { registerLiveTrustFrameRoutes } from "./routes/live-trust-frame.js";
import { registerProviderCommandCenterRoutes } from "./routes/provider-command-center.js";
import { registerCustomerCommandCenterRoutes } from "./routes/customer-command-center.js";
import { registerPlatformControlTowerRoutes } from "./routes/platform-control-tower.js";
import { registerReleaseReadinessRoutes } from "./routes/release-readiness.js";
import { registerMarketplaceIntelligenceRoutes } from "./routes/marketplace-intelligence.js";
import { registerExecutiveCommandCenterRoutes } from "./routes/executive-command-center.js";
import { registerLaunchSimulationRoutes } from "./routes/launch-simulation.js";
import { registerInvestorReadinessRoutes } from "./routes/investor-readiness.js";
import { registerGovernmentPartnershipRoutes } from "./routes/government-partnership.js";
import { registerStrategicOperatingRoutes } from "./routes/strategic-operating-system.js";
import { registerMissionControlRoutes } from "./routes/mission-control.js";
import { registerExecutiveExperienceRoutes } from "./routes/executive-experience.js";
import { registerArchitectureReviewRoutes } from "./routes/architecture-review.js";
import { registerApiAuditRoutes } from "./routes/api-audit.js";
import { registerProductionReadinessRoutes } from "./routes/production-readiness.js";
import { registerSecurityReadinessRoutes } from "./routes/security-readiness.js";
import { registerPlatformOperationsRoutes } from "./routes/platform-operations.js";
import { registerLaunchControlRoutes } from "./routes/launch-control.js";
import { registerPostLaunchMonitoringRoutes } from "./routes/post-launch-monitoring.js";
import { registerBusinessIntelligenceRoutes } from "./routes/business-intelligence.js";
import { registerExecutiveUxReadinessRoutes } from "./routes/executive-ux-readiness.js";
import { registerBrowserExperienceCompletenessRoutes } from "./routes/browser-experience-completeness.js";
import { registerOperatorSurfaceNavigationRoutes } from "./routes/operator-surface-navigation.js";
import { registerOperatorExperienceIntegrityRoutes } from "./routes/operator-experience-integrity.js";
import { registerOperatorOnboardingReadinessRoutes } from "./routes/operator-onboarding-readiness.js";
import { registerActionBlueprintRoutes } from "./routes/action-blueprint.js";
import { registerProfessionOntologyRoutes } from "./routes/profession-ontology.js";
import { registerProjectDecompositionRoutes } from "./routes/project-decomposition.js";
import { registerTekrrIntelligenceRoutes } from "./routes/tekrr-intelligence.js";
import { registerExecutionBlueprintRoutes } from "./routes/execution-blueprint.js";
import { registerBlueprintGovernanceRoutes } from "./routes/blueprint-governance.js";
import { registerMarketplaceCompilationRoutes } from "./routes/marketplace-compilation.js";
import { registerIntelligentPricingRoutes } from "./routes/intelligent-pricing.js";
import { registerIntelligentCommissionRoutes } from "./routes/intelligent-commission.js";
import { registerPersonalAssistantRoutes } from "./routes/personal-assistant.js";
import { registerDevelopMeRoutes } from "./routes/develop-me.js";
import { registerLearnByActionRoutes } from "./routes/learn-by-action.js";
import { registerExpertNetworkRoutes } from "./routes/expert-network.js";
import { registerTeamBuilderRoutes } from "./routes/team-builder.js";
import { registerKnowledgeBankRoutes } from "./routes/knowledge-bank.js";
import { registerIntelligenceOrchestrationRoutes } from "./routes/intelligence-orchestration.js";
import { registerBrowserSurfaceRoutes } from "./routes/browser-surface.js";
import { registerBrowserStaticRoutes } from "./routes/browser-static.js";
import type { GovernmentPartnershipService } from "../experience/government-partnership/application/government-partnership-service.js";
import type { StrategicOperatingService } from "../experience/strategic-operating-system/application/strategic-operating-service.js";
import type { MissionControlService } from "../experience/mission-control/application/mission-control-service.js";
import type { ExecutiveExperienceService } from "../experience/executive-experience/application/executive-experience-service.js";
import type { ArchitectureReviewService } from "../experience/architecture-review/application/architecture-review-service.js";
import type { ApiAuditService } from "../experience/api-audit/application/api-audit-service.js";
import type { ProductionReadinessService } from "../experience/production-readiness/application/production-readiness-service.js";
import type { SecurityReadinessService } from "../experience/security-readiness/application/security-readiness-service.js";
import type { PlatformOperationsService } from "../experience/platform-operations/application/platform-operations-service.js";
import type { LaunchControlService } from "../experience/launch-control/application/launch-control-service.js";
import type { PostLaunchMonitoringService } from "../experience/post-launch-monitoring/application/post-launch-monitoring-service.js";
import type { BusinessIntelligenceService } from "../experience/business-intelligence/application/business-intelligence-service.js";
import type { ExecutiveUxReadinessService } from "../experience/executive-ux-readiness/application/executive-ux-readiness-service.js";
import type { BrowserExperienceCompletenessService } from "../experience/browser-experience-completeness/application/browser-experience-completeness-service.js";
import type { OperatorSurfaceNavigationService } from "../experience/operator-surface-navigation/application/operator-surface-navigation-service.js";
import type { OperatorExperienceIntegrityService } from "../experience/operator-experience-integrity/application/operator-experience-integrity-service.js";
import type { OperatorOnboardingReadinessService } from "../experience/operator-onboarding-readiness/application/operator-onboarding-readiness-service.js";
import type { ActionBlueprintService } from "../action-blueprint/application/action-blueprint-service.js";
import type { ProfessionOntologyService } from "../profession-ontology/application/profession-ontology-service.js";
import type { ProjectDecompositionService } from "../project-decomposition/application/project-decomposition-service.js";
import type { TekrrIntelligenceService } from "../tekrr-intelligence/application/tekrr-intelligence-service.js";
import type { ExecutionBlueprintService } from "../execution-blueprint/application/execution-blueprint-service.js";
import type { BlueprintGovernanceService } from "../blueprint-governance/application/blueprint-governance-service.js";
import type { MarketplaceCompilationService } from "../marketplace-compilation/application/marketplace-compilation-service.js";
import type { IntelligentPricingService } from "../intelligent-pricing/application/intelligent-pricing-service.js";
import type { IntelligentCommissionService } from "../intelligent-commission/application/intelligent-commission-service.js";
import type { PersonalAssistantService } from "../personal-assistant/application/personal-assistant-service.js";
import type { DevelopMeService } from "../develop-me/application/develop-me-service.js";
import type { LearnByActionService } from "../learn-by-action/application/learn-by-action-service.js";
import type { ExpertNetworkService } from "../expert-network/application/expert-network-service.js";
import type { TeamBuilderService } from "../team-builder/application/team-builder-service.js";
import type { KnowledgeBankService } from "../knowledge-bank/application/knowledge-bank-service.js";
import type { IntelligenceOrchestrationService } from "../intelligence-orchestration/application/intelligence-orchestration-service.js";
import type { LivingOnboardingService } from "../living-experience/onboarding/application/living-onboarding-service.js";
import type { ProfessionalHomeService } from "../living-experience/professional-home/application/professional-home-service.js";
import type { LivingPassportService } from "../living-experience/professional-passport/application/living-passport-service.js";
import type { LivingLiveFrameService } from "../living-experience/live-frame/application/living-live-frame-service.js";
import type { LivingJourneyService } from "../living-experience/professional-journey/application/living-journey-service.js";
import type { LivingTodayIActedService } from "../living-experience/today-i-acted/application/living-today-i-acted-service.js";
import type { LivingOpportunitiesService } from "../living-experience/opportunities/application/living-opportunities-service.js";
import type { LivingPartnerEcosystemService } from "../living-experience/partner-ecosystem/application/living-partner-ecosystem-service.js";
import type { LivingProfessionalCommunityService } from "../living-experience/professional-community/application/living-professional-community-service.js";
import type { LivingProfessionalCoachService } from "../living-experience/professional-coach/application/living-professional-coach-service.js";
import type { LivingActionPlannerService } from "../living-experience/action-planner/application/living-action-planner-service.js";
import type { LivingProfessionalImpactService } from "../living-experience/professional-impact/application/living-professional-impact-service.js";
import type { LivingProfessionalIdentityService } from "../living-experience/professional-identity/application/living-professional-identity-service.js";
import type { LivingProfessionalIntelligenceService } from "../living-experience/professional-intelligence/application/living-professional-intelligence-service.js";
import { registerLivingOnboardingRoutes } from "./routes/living-onboarding.js";
import { registerProfessionalHomeRoutes } from "./routes/professional-home.js";
import { registerLivingPassportRoutes } from "./routes/living-passport.js";
import { registerLivingLiveFrameRoutes } from "./routes/living-live-frame.js";
import { registerLivingJourneyRoutes } from "./routes/living-journey.js";
import { registerLivingTodayIActedRoutes } from "./routes/living-today-i-acted.js";
import { registerLivingOpportunitiesRoutes } from "./routes/living-opportunities.js";
import { registerLivingPartnerEcosystemRoutes } from "./routes/living-partner-ecosystem.js";
import { registerLivingProfessionalCommunityRoutes } from "./routes/living-professional-community.js";
import { registerLivingProfessionalCoachRoutes } from "./routes/living-professional-coach.js";
import { registerLivingActionPlannerRoutes } from "./routes/living-action-planner.js";
import { registerLivingProfessionalImpactRoutes } from "./routes/living-professional-impact.js";
import { registerLivingProfessionalIdentityRoutes } from "./routes/living-professional-identity.js";
import { registerLivingProfessionalIntelligenceRoutes } from "./routes/living-professional-intelligence.js";
import type { BrowserSurfaceService } from "../browser-surface/application/browser-surface-service.js";
import type { BrowserStaticService } from "../browser-static/application/browser-static-service.js";
import type { InvestorReadinessService } from "../experience/investor-readiness/application/investor-readiness-service.js";
import type { LaunchSimulationService } from "../experience/launch-simulation/application/launch-simulation-service.js";
import type { ExecutiveCommandCenterService } from "../experience/executive-command-center/application/executive-command-center-service.js";
import type { MarketplaceIntelligenceService } from "../experience/marketplace-intelligence/application/marketplace-intelligence-service.js";
import { registerPlatformExperienceRoutes } from "./routes/platform.js";
import { createServiceAuthMiddleware } from "./middleware/service-auth.js";
import { createRevalidationMiddleware } from "./middleware/revalidate.js";
import { registerActionRoutes, registerContractActionRoutes } from "./routes/actions.js";
import { registerContractRoutes } from "./routes/contracts.js";
import { registerEvidenceRoutes } from "./routes/evidence.js";
import { registerIssueRoutes } from "./routes/issues.js";
import { registerInternalContractRoutes } from "./routes/internal/contracts.js";
import { registerAiActionRoutes } from "./routes/ai-actions.js";
import { registerAiRequirementRoutes } from "./routes/ai-requirements.js";
import { registerAiContractRoutes } from "./routes/ai-contracts.js";
import { registerAiTrustRoutes } from "./routes/ai-trust.js";
import { registerAiMatchingRoutes } from "./routes/ai-matching.js";
import { registerAiPricingRoutes } from "./routes/ai-pricing.js";
import { registerAiNegotiationRoutes } from "./routes/ai-negotiation.js";
import { registerAiWorkflowRoutes } from "./routes/ai-workflow.js";
import { registerAiProviderRoutes } from "./routes/ai-providers.js";

export interface AppDependencies {
  config: AppConfig;
  logger: Logger;
  db: DbPool;
  idempotency: IdempotencyService;
  jwt: JwtService;
  sessions: SessionStore;
  auth: AuthService;
  registration: RegistrationService;
  profile: ProfileService;
  verification: VerificationService;
  revalidation: IdentityRevalidationService;
  actions: ActionService;
  contracts: ContractEngineService;
  execution: ExecutionService;
  evaluation: EvaluationService;
  issues: IssueService;
  actionIntelligence: ActionIntelligenceService;
  requirementIntelligence: RequirementIntelligenceService;
  contractIntelligence: ContractIntelligenceService;
  trustIntelligence: TrustIntelligenceService;
  matchingIntelligence: MatchingIntelligenceService;
  pricingIntelligence: PricingIntelligenceService;
  negotiationIntelligence: NegotiationIntelligenceService;
  workflowIntelligence: WorkflowIntelligenceService;
  providerIntelligence: ProviderIntelligenceService;
  experience: ExperienceServices;
  trustScore: TrustScoreService;
  providerProfile: ProviderProfileService;
  requestIntelligence: RequestIntelligenceService;
  matchContractConversion: MatchContractConversionService;
  customerDashboard: CustomerDashboardService;
  providerDashboard: ProviderDashboardService;
  adminConsole: AdminConsoleService;
  eventInbox: EventInboxService;
  discovery: DiscoveryService;
  platformAnalytics: PlatformAnalyticsService;
  homeExperience: HomeExperienceService;
  liveFrameExperience: LiveFrameExperienceService;
  contractJourney: ContractJourneyService;
  actionEconomy: ActionEconomyService;
  requestMatchExperience: RequestMatchExperienceService;
  escrowPaymentExperience: EscrowPaymentExperienceService;
  trustReputationExperience: TrustReputationExperienceService;
  discoveryMatching: DiscoveryMatchingService;
  professionalPassport: ProfessionalPassportService;
  professionalSeals: ProfessionalSealsService;
  liveTrustFrame: LiveTrustFrameService;
  providerCommandCenter: ProviderCommandCenterService;
  customerCommandCenter: CustomerCommandCenterService;
  platformControlTower: PlatformControlTowerService;
  marketplaceIntelligence: MarketplaceIntelligenceService;
  executiveCommandCenter: ExecutiveCommandCenterService;
  launchSimulation: LaunchSimulationService;
  investorReadiness: InvestorReadinessService;
  governmentPartnership: GovernmentPartnershipService;
  strategicOperatingSystem: StrategicOperatingService;
  missionControl: MissionControlService;
  executiveExperience: ExecutiveExperienceService;
  architectureReview: ArchitectureReviewService;
  apiAudit: ApiAuditService;
  productionReadiness: ProductionReadinessService;
  securityReadiness: SecurityReadinessService;
  platformOperations: PlatformOperationsService;
  launchControl: LaunchControlService;
  postLaunchMonitoring: PostLaunchMonitoringService;
  businessIntelligence: BusinessIntelligenceService;
  executiveUxReadiness: ExecutiveUxReadinessService;
  browserExperienceCompleteness: BrowserExperienceCompletenessService;
  operatorSurfaceNavigation: OperatorSurfaceNavigationService;
  operatorExperienceIntegrity: OperatorExperienceIntegrityService;
  operatorOnboardingReadiness: OperatorOnboardingReadinessService;
  actionBlueprint: ActionBlueprintService;
  professionOntology: ProfessionOntologyService;
  projectDecomposition: ProjectDecompositionService;
  tekrrIntelligence: TekrrIntelligenceService;
  executionBlueprint: ExecutionBlueprintService;
  blueprintGovernance: BlueprintGovernanceService;
  marketplaceCompilation: MarketplaceCompilationService;
  intelligentPricing: IntelligentPricingService;
  intelligentCommission: IntelligentCommissionService;
  personalAssistant: PersonalAssistantService;
  developMe: DevelopMeService;
  learnByAction: LearnByActionService;
  expertNetwork: ExpertNetworkService;
  teamBuilder: TeamBuilderService;
  knowledgeBank: KnowledgeBankService;
  intelligenceOrchestration: IntelligenceOrchestrationService;
  livingOnboarding: LivingOnboardingService;
  professionalHome: ProfessionalHomeService;
  livingPassport: LivingPassportService;
  livingLiveFrame: LivingLiveFrameService;
  livingJourney: LivingJourneyService;
  livingTodayIActed: LivingTodayIActedService;
  livingOpportunities: LivingOpportunitiesService;
  livingPartnerEcosystem: LivingPartnerEcosystemService;
  livingProfessionalCommunity: LivingProfessionalCommunityService;
  livingProfessionalCoach: LivingProfessionalCoachService;
  livingActionPlanner: LivingActionPlannerService;
  livingProfessionalImpact: LivingProfessionalImpactService;
  livingProfessionalIdentity: LivingProfessionalIdentityService;
  livingProfessionalIntelligence: LivingProfessionalIntelligenceService;
  browserSurface: BrowserSurfaceService;
  browserStatic: BrowserStaticService;
  releaseReadinessCenter: ReleaseReadinessCenterService;
  securityAuth: SecurityAuthKernelService;
  ownershipRegistry: OwnershipRegistry;
  securityAudit: SecurityAuditService;
}

export async function buildServer(deps: AppDependencies) {
  const app = Fastify({
    logger: resolveFastifyLogger(deps.config),
    requestIdHeader: "x-request-id",
    genReqId: () => randomUUID(),
  });

  await app.register(cookie);

  app.addHook("onRequest", requestIdMiddleware);
  app.addHook("preHandler", createIdempotencyPreHandler(deps.idempotency));
  app.addHook(
    "preHandler",
    createAuthenticateMiddleware({
      jwt: deps.jwt,
      sessions: deps.sessions,
      config: deps.config,
    })
  );
  app.addHook("preHandler", requireAuthMiddleware);
  app.addHook("preHandler", createRevalidationMiddleware(deps.revalidation));
  app.addHook("preHandler", createServiceAuthMiddleware(deps.config.serviceId));
  app.addHook("onSend", createIdempotencyOnSend(deps.idempotency));
  app.setErrorHandler(errorHandler);

  await registerHealthRoutes(app, deps.db);
  await registerBrowserSurfaceRoutes(app, deps.browserSurface);
  await registerBrowserStaticRoutes(app, deps.browserStatic);
  await registerAuthRoutes(app, {
    auth: deps.auth,
    registration: deps.registration,
  });
  await registerSecurityAuthRoutes(app, { securityAuth: deps.securityAuth });
  await registerIdentityRoutes(app, deps.profile);
  await registerVerificationRoutes(app, deps.verification);
  await registerActionRoutes(app, deps.actions);
  await registerContractActionRoutes(app, deps.contracts);
  await registerContractRoutes(app, deps.contracts, deps.evaluation);
  await registerEvidenceRoutes(app, deps.execution);
  await registerIssueRoutes(app, deps.issues);
  await registerAiActionRoutes(app, deps.actionIntelligence);
  await registerAiRequirementRoutes(app, deps.requirementIntelligence);
  await registerAiContractRoutes(app, deps.contractIntelligence);
  await registerAiTrustRoutes(app, deps.trustIntelligence);
  await registerAiMatchingRoutes(app, deps.matchingIntelligence);
  await registerAiPricingRoutes(app, deps.pricingIntelligence);
  await registerAiNegotiationRoutes(app, deps.negotiationIntelligence);
  await registerAiWorkflowRoutes(app, deps.workflowIntelligence);
  await registerAiProviderRoutes(app, deps.providerIntelligence);
  await registerInternalContractRoutes(app, deps.contracts);
  await registerEscrowExperienceRoutes(app, deps.experience.escrow);
  await registerExecutionExperienceRoutes(app, deps.experience.execution);
  await registerEvidenceReadRoutes(app, deps.experience.evidence);
  await registerDisputesReadRoutes(app, deps.experience.dispute);
  await registerTrustExperienceRoutes(app, deps.experience.trust);
  await registerTrustReputationRoutes(app, deps.trustScore);
  await registerProviderRoutes(app, deps.providerProfile);
  await registerProviderDashboardRoutes(app, deps.providerDashboard);
  await registerRequestRoutes(app, deps.requestIntelligence);
  await registerConversionRoutes(app, deps.matchContractConversion);
  await registerCustomerDashboardRoutes(app, deps.customerDashboard);
  await registerAdminConsoleRoutes(app, deps.adminConsole);
  await registerNotificationRoutes(app, deps.eventInbox);
  await registerDiscoveryRoutes(app, deps.discovery);
  await registerAnalyticsRoutes(app, deps.platformAnalytics);
  await registerHomeRoutes(app, deps.homeExperience);
  await registerLiveFrameRoutes(app, deps.liveFrameExperience);
  await registerContractJourneyRoutes(app, deps.contractJourney);
  await registerActionEconomyRoutes(app, deps.actionEconomy);
  await registerRequestMatchRoutes(app, deps.requestMatchExperience);
  await registerEscrowPaymentRoutes(app, deps.escrowPaymentExperience);
  await registerTrustReputationExperienceRoutes(app, deps.trustReputationExperience);
  await registerDiscoveryMatchingRoutes(app, deps.discoveryMatching);
  await registerProfessionalPassportRoutes(app, deps.professionalPassport);
  await registerProfessionalSealsRoutes(app, deps.professionalSeals);
  await registerLiveTrustFrameRoutes(app, deps.liveTrustFrame);
  await registerProviderCommandCenterRoutes(app, deps.providerCommandCenter);
  await registerCustomerCommandCenterRoutes(app, deps.customerCommandCenter);
  await registerPlatformControlTowerRoutes(app, deps.platformControlTower);
  await registerMarketplaceIntelligenceRoutes(app, deps.marketplaceIntelligence);
  await registerExecutiveCommandCenterRoutes(app, deps.executiveCommandCenter);
  await registerLaunchSimulationRoutes(app, deps.launchSimulation);
  await registerInvestorReadinessRoutes(app, deps.investorReadiness);
  await registerGovernmentPartnershipRoutes(app, deps.governmentPartnership);
  await registerStrategicOperatingRoutes(app, deps.strategicOperatingSystem);
  await registerMissionControlRoutes(app, deps.missionControl);
  await registerExecutiveExperienceRoutes(app, deps.executiveExperience);
  await registerArchitectureReviewRoutes(app, deps.architectureReview);
  await registerApiAuditRoutes(app, deps.apiAudit);
  await registerProductionReadinessRoutes(app, deps.productionReadiness);
  await registerSecurityReadinessRoutes(app, deps.securityReadiness);
  await registerPlatformOperationsRoutes(app, deps.platformOperations);
  await registerLaunchControlRoutes(app, deps.launchControl);
  await registerPostLaunchMonitoringRoutes(app, deps.postLaunchMonitoring);
  await registerBusinessIntelligenceRoutes(app, deps.businessIntelligence);
  await registerExecutiveUxReadinessRoutes(app, deps.executiveUxReadiness);
  await registerBrowserExperienceCompletenessRoutes(app, deps.browserExperienceCompleteness);
  await registerOperatorSurfaceNavigationRoutes(app, deps.operatorSurfaceNavigation);
  await registerOperatorExperienceIntegrityRoutes(app, deps.operatorExperienceIntegrity);
  await registerOperatorOnboardingReadinessRoutes(app, deps.operatorOnboardingReadiness);
  await registerActionBlueprintRoutes(app, deps.actionBlueprint);
  await registerProfessionOntologyRoutes(app, deps.professionOntology);
  await registerProjectDecompositionRoutes(app, deps.projectDecomposition);
  await registerTekrrIntelligenceRoutes(app, deps.tekrrIntelligence);
  await registerExecutionBlueprintRoutes(app, deps.executionBlueprint);
  await registerBlueprintGovernanceRoutes(app, deps.blueprintGovernance);
  await registerMarketplaceCompilationRoutes(app, deps.marketplaceCompilation);
  await registerIntelligentPricingRoutes(app, deps.intelligentPricing);
  await registerIntelligentCommissionRoutes(app, deps.intelligentCommission);
  await registerPersonalAssistantRoutes(app, deps.personalAssistant);
  await registerDevelopMeRoutes(app, deps.developMe);
  await registerLearnByActionRoutes(app, deps.learnByAction);
  await registerExpertNetworkRoutes(app, deps.expertNetwork);
  await registerTeamBuilderRoutes(app, deps.teamBuilder);
  await registerKnowledgeBankRoutes(app, deps.knowledgeBank);
  await registerIntelligenceOrchestrationRoutes(app, deps.intelligenceOrchestration);
  await registerLivingOnboardingRoutes(app, deps.livingOnboarding);
  await registerProfessionalHomeRoutes(app, deps.professionalHome);
  await registerLivingPassportRoutes(app, deps.livingPassport);
  await registerLivingLiveFrameRoutes(app, deps.livingLiveFrame);
  await registerLivingJourneyRoutes(app, deps.livingJourney);
  await registerLivingTodayIActedRoutes(app, deps.livingTodayIActed);
  await registerLivingOpportunitiesRoutes(app, deps.livingOpportunities);
  await registerLivingPartnerEcosystemRoutes(app, deps.livingPartnerEcosystem);
  await registerLivingProfessionalCommunityRoutes(app, deps.livingProfessionalCommunity);
  await registerLivingProfessionalCoachRoutes(app, deps.livingProfessionalCoach);
  await registerLivingActionPlannerRoutes(app, deps.livingActionPlanner);
  await registerLivingProfessionalImpactRoutes(app, deps.livingProfessionalImpact);
  await registerLivingProfessionalIdentityRoutes(app, deps.livingProfessionalIdentity);
  await registerLivingProfessionalIntelligenceRoutes(app, deps.livingProfessionalIntelligence);
  await registerReleaseReadinessRoutes(app, deps.releaseReadinessCenter);
  await registerPlatformExperienceRoutes(app, deps.experience.platform);

  return app;
}
