export {
  buildAnalyticsSummary,
  buildContractMetrics,
  buildConversionMetrics,
  buildDiscoveryMetrics,
  buildEscrowMetrics,
  buildExecutionMetrics,
  buildGrowthMetrics,
  buildPlatformMetrics,
  buildRateMetric,
  buildRevenueMetrics,
  buildRollingCounts,
  buildTrendIndicator,
  buildTrustMetrics,
  deriveTrendDirection,
  toAnalyticsSummaryView,
  toContractMetricsView,
  toConversionMetricsView,
  toDiscoveryMetricsView,
  toEscrowMetricsView,
  toExecutionMetricsView,
  toGrowthMetricsView,
  toPlatformMetricsView,
  toRateMetricView,
  toRevenueMetricsView,
  toRollingCountsView,
  toTrustMetricsView,
  type AnalyticsSummary,
  type AnalyticsSummaryView,
  type ContractMetrics,
  type ContractMetricsView,
  type ConversionMetrics,
  type ConversionMetricsView,
  type DiscoveryMetrics,
  type DiscoveryMetricsView,
  type EscrowMetrics,
  type EscrowMetricsView,
  type ExecutionMetrics,
  type ExecutionMetricsView,
  type GrowthMetrics,
  type GrowthMetricsView,
  type PlatformAnalyticsSnapshot,
  type PlatformMetrics,
  type PlatformMetricsView,
  type RateMetric,
  type RateMetricView,
  type RevenueMetrics,
  type RevenueMetricsView,
  type RollingCounts,
  type RollingCountsView,
  type TrendDirection,
  type TrendIndicator,
  type TrustMetrics,
  type TrustMetricsView,
} from "./domain/platform-analytics.js";
export {
  PlatformAnalyticsService,
  createAnalyticsModule,
  createPlatformAnalyticsService,
  type AnalyticsModule,
} from "./application/platform-analytics-service.js";
export {
  PlatformAnalyticsRepository,
  platformAnalyticsRepository,
} from "./infrastructure/platform-analytics-repository.js";
