import type { StagePhase } from "../domain/action-planning-schema.js";

export interface PlanTaskTemplate {
  taskId: string;
  phase: StagePhase;
  order: number;
  title: string;
  description: string;
  estimatedMinutes: { min: number; max: number };
  skillIds: string[];
  resourceIds: string[];
  parallelCapable: boolean;
  dependsOnTaskIds: string[];
}

export interface PlanTemplate {
  canonicalActionId: string;
  goal: string;
  tasks: PlanTaskTemplate[];
}

export const PLAN_TEMPLATES: PlanTemplate[] = [
  {
    canonicalActionId: "act.move.room_contents",
    goal: "Move a room's contents safely",
    tasks: [
      {
        taskId: "task.move.assess",
        phase: "intake",
        order: 1,
        title: "Assess room and inventory items",
        description: "Walk through source room and list furniture, fragile items, and constraints.",
        estimatedMinutes: { min: 15, max: 30 },
        skillIds: ["sk.spatial_planning"],
        resourceIds: [],
        parallelCapable: false,
        dependsOnTaskIds: [],
      },
      {
        taskId: "task.move.schedule",
        phase: "planning",
        order: 2,
        title: "Schedule move window",
        description: "Confirm access time with customer and second handler availability.",
        estimatedMinutes: { min: 10, max: 20 },
        skillIds: ["sk.scheduling"],
        resourceIds: ["res.calendar"],
        parallelCapable: true,
        dependsOnTaskIds: ["task.move.assess"],
      },
      {
        taskId: "task.move.inspect",
        phase: "planning",
        order: 3,
        title: "Inspect site readiness",
        description: "Verify pathways and destination room are ready per inspection checklist.",
        estimatedMinutes: { min: 15, max: 25 },
        skillIds: ["sk.site_assessment"],
        resourceIds: ["res.checklist"],
        parallelCapable: true,
        dependsOnTaskIds: ["task.move.assess"],
      },
      {
        taskId: "task.move.prepare",
        phase: "preparation",
        order: 4,
        title: "Prepare protection and equipment",
        description: "Lay floor protection, pad corners, and stage dolly and straps.",
        estimatedMinutes: { min: 20, max: 40 },
        skillIds: ["sk.manual_handling"],
        resourceIds: ["res.dolly", "res.pads"],
        parallelCapable: false,
        dependsOnTaskIds: ["task.move.schedule", "task.move.inspect"],
      },
      {
        taskId: "task.move.disassemble",
        phase: "preparation",
        order: 5,
        title: "Disassemble oversized items",
        description: "Remove modular parts blocking narrow passages.",
        estimatedMinutes: { min: 30, max: 60 },
        skillIds: ["sk.manual_handling"],
        resourceIds: ["res.toolkit"],
        parallelCapable: false,
        dependsOnTaskIds: ["task.move.prepare"],
      },
      {
        taskId: "task.move.execute",
        phase: "execution",
        order: 6,
        title: "Move items in priority order",
        description: "Transport boxes, medium furniture, then heavy pieces with two handlers.",
        estimatedMinutes: { min: 60, max: 180 },
        skillIds: ["sk.manual_handling", "sk.spatial_planning"],
        resourceIds: ["res.dolly", "res.pads", "res.helper"],
        parallelCapable: false,
        dependsOnTaskIds: ["task.move.disassemble"],
      },
      {
        taskId: "task.move.reassemble",
        phase: "verification",
        order: 7,
        title: "Reassemble and verify placement",
        description: "Reinstall parts and confirm stable placement in destination room.",
        estimatedMinutes: { min: 20, max: 45 },
        skillIds: ["sk.manual_handling"],
        resourceIds: ["res.toolkit"],
        parallelCapable: false,
        dependsOnTaskIds: ["task.move.execute"],
      },
      {
        taskId: "task.move.document",
        phase: "closure",
        order: 8,
        title: "Document completion with photos",
        description: "Capture after photos and complete service report.",
        estimatedMinutes: { min: 10, max: 20 },
        skillIds: ["sk.reporting"],
        resourceIds: ["res.report_template"],
        parallelCapable: false,
        dependsOnTaskIds: ["task.move.reassemble"],
      },
    ],
  },
  {
    canonicalActionId: "act.clean.apartment_full",
    goal: "Clean an apartment thoroughly",
    tasks: [
      {
        taskId: "task.clean.walkthrough",
        phase: "intake",
        order: 1,
        title: "Walk-through and supply check",
        description: "Identify priority zones and confirm cleaning supplies.",
        estimatedMinutes: { min: 10, max: 20 },
        skillIds: ["sk.surface_care"],
        resourceIds: ["res.cleaning_agents"],
        parallelCapable: false,
        dependsOnTaskIds: [],
      },
      {
        taskId: "task.clean.schedule",
        phase: "planning",
        order: 2,
        title: "Confirm cleaning schedule",
        description: "Lock appointment window and room access sequence.",
        estimatedMinutes: { min: 5, max: 15 },
        skillIds: ["sk.scheduling"],
        resourceIds: ["res.calendar"],
        parallelCapable: true,
        dependsOnTaskIds: ["task.clean.walkthrough"],
      },
      {
        taskId: "task.clean.declutter",
        phase: "preparation",
        order: 3,
        title: "Declutter surfaces",
        description: "Clear counters and floors for full surface access.",
        estimatedMinutes: { min: 20, max: 40 },
        skillIds: ["sk.surface_care"],
        resourceIds: [],
        parallelCapable: false,
        dependsOnTaskIds: ["task.clean.schedule"],
      },
      {
        taskId: "task.clean.kitchen_bath",
        phase: "execution",
        order: 4,
        title: "Deep clean kitchen and bathroom",
        description: "Sanitize fixtures and high-touch surfaces.",
        estimatedMinutes: { min: 60, max: 120 },
        skillIds: ["sk.sanitation"],
        resourceIds: ["res.cleaning_agents"],
        parallelCapable: true,
        dependsOnTaskIds: ["task.clean.declutter"],
      },
      {
        taskId: "task.clean.living",
        phase: "execution",
        order: 5,
        title: "Dust and wipe living areas",
        description: "Dust surfaces, wipe switches, clean mirrors.",
        estimatedMinutes: { min: 45, max: 90 },
        skillIds: ["sk.surface_care"],
        resourceIds: ["res.vacuum"],
        parallelCapable: true,
        dependsOnTaskIds: ["task.clean.declutter"],
      },
      {
        taskId: "task.clean.floors",
        phase: "execution",
        order: 6,
        title: "Vacuum and mop all floors",
        description: "Finish floors working from far rooms toward exit.",
        estimatedMinutes: { min: 30, max: 60 },
        skillIds: ["sk.surface_care"],
        resourceIds: ["res.vacuum", "res.mop"],
        parallelCapable: false,
        dependsOnTaskIds: ["task.clean.kitchen_bath", "task.clean.living"],
      },
      {
        taskId: "task.clean.qa",
        phase: "verification",
        order: 7,
        title: "Quality check inspection",
        description: "Run QA rubric on all cleaned rooms.",
        estimatedMinutes: { min: 15, max: 30 },
        skillIds: ["sk.quality_assurance"],
        resourceIds: ["res.qa_rubric"],
        parallelCapable: false,
        dependsOnTaskIds: ["task.clean.floors"],
      },
      {
        taskId: "task.clean.report",
        phase: "closure",
        order: 8,
        title: "Complete service report",
        description: "Document checklist and sign-off.",
        estimatedMinutes: { min: 10, max: 20 },
        skillIds: ["sk.reporting"],
        resourceIds: ["res.report_template"],
        parallelCapable: false,
        dependsOnTaskIds: ["task.clean.qa"],
      },
    ],
  },
  {
    canonicalActionId: "act.deliver.document_secure",
    goal: "Deliver a document securely",
    tasks: [
      {
        taskId: "task.deliver.verify",
        phase: "intake",
        order: 1,
        title: "Verify document and recipient",
        description: "Confirm document identity, recipient, and delivery window.",
        estimatedMinutes: { min: 5, max: 15 },
        skillIds: ["sk.custody"],
        resourceIds: ["res.document"],
        parallelCapable: false,
        dependsOnTaskIds: [],
      },
      {
        taskId: "task.deliver.window",
        phase: "planning",
        order: 2,
        title: "Coordinate delivery window",
        description: "Align timing with recipient availability.",
        estimatedMinutes: { min: 5, max: 15 },
        skillIds: ["sk.logistics_coord"],
        resourceIds: ["res.recipient_contact"],
        parallelCapable: false,
        dependsOnTaskIds: ["task.deliver.verify"],
      },
      {
        taskId: "task.deliver.pack",
        phase: "preparation",
        order: 3,
        title: "Seal document packaging",
        description: "Place document in tamper-evident envelope.",
        estimatedMinutes: { min: 5, max: 10 },
        skillIds: ["sk.custody"],
        resourceIds: ["res.envelope"],
        parallelCapable: false,
        dependsOnTaskIds: ["task.deliver.window"],
      },
      {
        taskId: "task.deliver.custody",
        phase: "preparation",
        order: 4,
        title: "Initialize custody log",
        description: "Record pickup timestamp and handler identity.",
        estimatedMinutes: { min: 5, max: 10 },
        skillIds: ["sk.recordkeeping"],
        resourceIds: ["res.log_template"],
        parallelCapable: true,
        dependsOnTaskIds: ["task.deliver.pack"],
      },
      {
        taskId: "task.deliver.transport",
        phase: "execution",
        order: 5,
        title: "Transport document",
        description: "Deliver via planned route without exposure to loss.",
        estimatedMinutes: { min: 20, max: 90 },
        skillIds: ["sk.navigation", "sk.custody"],
        resourceIds: ["res.transport"],
        parallelCapable: false,
        dependsOnTaskIds: ["task.deliver.custody"],
      },
      {
        taskId: "task.deliver.proof",
        phase: "verification",
        order: 6,
        title: "Obtain proof of delivery",
        description: "Collect signature or timestamp confirmation.",
        estimatedMinutes: { min: 5, max: 15 },
        skillIds: ["sk.custody"],
        resourceIds: [],
        parallelCapable: false,
        dependsOnTaskIds: ["task.deliver.transport"],
      },
      {
        taskId: "task.deliver.close",
        phase: "closure",
        order: 7,
        title: "Close custody log",
        description: "Finalize custody timeline with delivery confirmation.",
        estimatedMinutes: { min: 5, max: 10 },
        skillIds: ["sk.recordkeeping"],
        resourceIds: ["res.log_template"],
        parallelCapable: false,
        dependsOnTaskIds: ["task.deliver.proof"],
      },
    ],
  },
  {
    canonicalActionId: "act.maint.fix_minor_issue",
    goal: "Fix a small home maintenance issue",
    tasks: [
      {
        taskId: "task.fix.diagnose",
        phase: "intake",
        order: 1,
        title: "Diagnose issue safely",
        description: "Inspect symptoms and confirm minor repair scope.",
        estimatedMinutes: { min: 10, max: 25 },
        skillIds: ["sk.diagnostics"],
        resourceIds: ["res.shutoff"],
        parallelCapable: false,
        dependsOnTaskIds: [],
      },
      {
        taskId: "task.fix.estimate",
        phase: "planning",
        order: 2,
        title: "Estimate repair cost",
        description: "Produce read-only price band estimate for customer approval.",
        estimatedMinutes: { min: 10, max: 25 },
        skillIds: ["sk.repair_pricing"],
        resourceIds: ["res.parts_catalog"],
        parallelCapable: false,
        dependsOnTaskIds: ["task.fix.diagnose"],
      },
      {
        taskId: "task.fix.inspect",
        phase: "planning",
        order: 3,
        title: "Pre-work site inspection",
        description: "Verify site safety and utility shutoff access.",
        estimatedMinutes: { min: 10, max: 20 },
        skillIds: ["sk.site_assessment"],
        resourceIds: ["res.checklist"],
        parallelCapable: true,
        dependsOnTaskIds: ["task.fix.diagnose"],
      },
      {
        taskId: "task.fix.gather",
        phase: "preparation",
        order: 4,
        title: "Gather tools and parts",
        description: "Collect toolkit and compatible replacement parts.",
        estimatedMinutes: { min: 10, max: 30 },
        skillIds: ["sk.diagnostics"],
        resourceIds: ["res.toolkit", "res.parts"],
        parallelCapable: false,
        dependsOnTaskIds: ["task.fix.estimate", "task.fix.inspect"],
      },
      {
        taskId: "task.fix.repair",
        phase: "execution",
        order: 5,
        title: "Apply targeted repair",
        description: "Tighten, replace, seal, or reset affected component.",
        estimatedMinutes: { min: 30, max: 90 },
        skillIds: ["sk.diagnostics", "sk.utility_safety"],
        resourceIds: ["res.toolkit"],
        parallelCapable: false,
        dependsOnTaskIds: ["task.fix.gather"],
      },
      {
        taskId: "task.fix.test",
        phase: "verification",
        order: 6,
        title: "Test and verify fix",
        description: "Run functional test to confirm issue resolved.",
        estimatedMinutes: { min: 10, max: 20 },
        skillIds: ["sk.diagnostics"],
        resourceIds: [],
        parallelCapable: false,
        dependsOnTaskIds: ["task.fix.repair"],
      },
      {
        taskId: "task.fix.document",
        phase: "closure",
        order: 7,
        title: "Document work performed",
        description: "Record parts used and test results.",
        estimatedMinutes: { min: 5, max: 15 },
        skillIds: ["sk.reporting"],
        resourceIds: ["res.report_template"],
        parallelCapable: false,
        dependsOnTaskIds: ["task.fix.test"],
      },
    ],
  },
  {
    canonicalActionId: "act.pro.prepare_service_request",
    goal: "Prepare a professional service request",
    tasks: [
      {
        taskId: "task.req.intent",
        phase: "intake",
        order: 1,
        title: "Capture service intent",
        description: "Record customer outcome and constraints.",
        estimatedMinutes: { min: 10, max: 20 },
        skillIds: ["sk.scoping"],
        resourceIds: ["res.brief"],
        parallelCapable: false,
        dependsOnTaskIds: [],
      },
      {
        taskId: "task.req.scope",
        phase: "planning",
        order: 2,
        title: "Define scope and boundaries",
        description: "List inclusions, exclusions, and access constraints.",
        estimatedMinutes: { min: 15, max: 30 },
        skillIds: ["sk.scoping"],
        resourceIds: ["res.brief"],
        parallelCapable: false,
        dependsOnTaskIds: ["task.req.intent"],
      },
      {
        taskId: "task.req.skills",
        phase: "planning",
        order: 3,
        title: "Map required skills and credentials",
        description: "Identify provider qualifications and licenses needed.",
        estimatedMinutes: { min: 10, max: 20 },
        skillIds: ["sk.requirements"],
        resourceIds: [],
        parallelCapable: true,
        dependsOnTaskIds: ["task.req.scope"],
      },
      {
        taskId: "task.req.estimate",
        phase: "planning",
        order: 4,
        title: "Estimate time and budget band",
        description: "Produce read-only price and duration estimate.",
        estimatedMinutes: { min: 10, max: 25 },
        skillIds: ["sk.pricing"],
        resourceIds: ["res.rate_card"],
        parallelCapable: true,
        dependsOnTaskIds: ["task.req.scope"],
      },
      {
        taskId: "task.req.schedule",
        phase: "preparation",
        order: 5,
        title: "Schedule coordination call",
        description: "Align customer availability for provider matching.",
        estimatedMinutes: { min: 10, max: 20 },
        skillIds: ["sk.scheduling"],
        resourceIds: ["res.calendar"],
        parallelCapable: false,
        dependsOnTaskIds: ["task.req.skills", "task.req.estimate"],
      },
      {
        taskId: "task.req.package",
        phase: "execution",
        order: 6,
        title: "Draft match-ready request package",
        description: "Assemble structured request with milestones and evidence expectations.",
        estimatedMinutes: { min: 15, max: 30 },
        skillIds: ["sk.scoping", "sk.requirements"],
        resourceIds: ["res.brief", "res.site_info"],
        parallelCapable: false,
        dependsOnTaskIds: ["task.req.schedule"],
      },
      {
        taskId: "task.req.contract_hints",
        phase: "verification",
        order: 7,
        title: "Prepare contract draft hints",
        description: "Map evidence gates to draft contract milestones — no contract created.",
        estimatedMinutes: { min: 10, max: 20 },
        skillIds: ["sk.contract_scoping"],
        resourceIds: ["res.contract_template"],
        parallelCapable: false,
        dependsOnTaskIds: ["task.req.package"],
      },
      {
        taskId: "task.req.review",
        phase: "closure",
        order: 8,
        title: "Review completion criteria",
        description: "Validate request package against acceptance criteria.",
        estimatedMinutes: { min: 10, max: 20 },
        skillIds: ["sk.scoping"],
        resourceIds: [],
        parallelCapable: false,
        dependsOnTaskIds: ["task.req.contract_hints"],
      },
    ],
  },
];

export function getPlanTemplate(canonicalActionId: string): PlanTemplate | undefined {
  return PLAN_TEMPLATES.find((template) => template.canonicalActionId === canonicalActionId);
}

export function listPlanTemplates(): PlanTemplate[] {
  return PLAN_TEMPLATES.map((template) => ({
    ...template,
    tasks: template.tasks.map((task) => ({ ...task, dependsOnTaskIds: [...task.dependsOnTaskIds] })),
  }));
}
