import type { FastifyInstance } from "fastify";
import { registerHealthRoutes } from "../api/routes/health.js";
import { registerAuthRoutes } from "../api/routes/auth.js";
import { registerSecurityAuthRoutes } from "../api/routes/security-auth.js";
import { registerIdentityRoutes } from "../api/routes/identity.js";
import { registerVerificationRoutes } from "../api/routes/verification.js";
import { registerActionRoutes, registerContractActionRoutes } from "../api/routes/actions.js";
import { registerContractRoutes } from "../api/routes/contracts.js";
import { registerEvidenceRoutes } from "../api/routes/evidence.js";
import { registerIssueRoutes } from "../api/routes/issues.js";
import { registerInternalContractRoutes } from "../api/routes/internal/contracts.js";
import { registerAiActionRoutes } from "../api/routes/ai-actions.js";
import { registerAiRequirementRoutes } from "../api/routes/ai-requirements.js";
import { registerAiContractRoutes } from "../api/routes/ai-contracts.js";
import { registerAiTrustRoutes } from "../api/routes/ai-trust.js";
import { registerAiMatchingRoutes } from "../api/routes/ai-matching.js";
import { registerAiPricingRoutes } from "../api/routes/ai-pricing.js";
import { registerAiNegotiationRoutes } from "../api/routes/ai-negotiation.js";
import { registerAiWorkflowRoutes } from "../api/routes/ai-workflow.js";
import { registerAiProviderRoutes } from "../api/routes/ai-providers.js";
import { registerEscrowExperienceRoutes } from "../api/routes/escrow.js";
import { registerExecutionExperienceRoutes } from "../api/routes/execution.js";
import { registerEvidenceReadRoutes } from "../api/routes/evidence-read.js";
import { registerDisputesReadRoutes } from "../api/routes/disputes-read.js";
import { registerTrustExperienceRoutes, registerTrustReputationRoutes } from "../api/routes/trust.js";
import { registerProviderRoutes } from "../api/routes/providers.js";
import { registerRequestRoutes } from "../api/routes/requests.js";
import { registerConversionRoutes } from "../api/routes/conversions.js";
import { registerCustomerDashboardRoutes } from "../api/routes/customer-dashboard.js";
import { registerProviderDashboardRoutes } from "../api/routes/provider-dashboard.js";
import { registerAdminConsoleRoutes } from "../api/routes/admin-console.js";
import { registerNotificationRoutes } from "../api/routes/notifications.js";
import { registerDiscoveryRoutes } from "../api/routes/discovery.js";
import { registerAnalyticsRoutes } from "../api/routes/analytics.js";
import { registerHomeRoutes } from "../api/routes/home.js";
import { registerLiveFrameRoutes } from "../api/routes/live-frame.js";
import { registerContractJourneyRoutes } from "../api/routes/contract-journey.js";
import { registerActionEconomyRoutes } from "../api/routes/action-economy.js";
import { registerRequestMatchRoutes } from "../api/routes/request-match.js";
import { registerEscrowPaymentRoutes } from "../api/routes/escrow-payment.js";
import { registerTrustReputationExperienceRoutes } from "../api/routes/trust-reputation.js";
import { registerDiscoveryMatchingRoutes } from "../api/routes/discovery-matching.js";
import { registerProfessionalPassportRoutes } from "../api/routes/professional-passport.js";
import { registerProfessionalSealsRoutes } from "../api/routes/professional-seals.js";
import { registerLiveTrustFrameRoutes } from "../api/routes/live-trust-frame.js";
import { registerProviderCommandCenterRoutes } from "../api/routes/provider-command-center.js";
import { registerCustomerCommandCenterRoutes } from "../api/routes/customer-command-center.js";
import { registerPlatformControlTowerRoutes } from "../api/routes/platform-control-tower.js";
import { registerReleaseReadinessRoutes } from "../api/routes/release-readiness.js";
import { registerMarketplaceIntelligenceRoutes } from "../api/routes/marketplace-intelligence.js";
import { registerExecutiveCommandCenterRoutes } from "../api/routes/executive-command-center.js";
import { registerLaunchSimulationRoutes } from "../api/routes/launch-simulation.js";
import { registerInvestorReadinessRoutes } from "../api/routes/investor-readiness.js";
import { registerGovernmentPartnershipRoutes } from "../api/routes/government-partnership.js";
import { registerStrategicOperatingRoutes } from "../api/routes/strategic-operating-system.js";
import { registerMissionControlRoutes } from "../api/routes/mission-control.js";
import { registerExecutiveExperienceRoutes } from "../api/routes/executive-experience.js";
import { registerArchitectureReviewRoutes } from "../api/routes/architecture-review.js";
import { registerApiAuditRoutes } from "../api/routes/api-audit.js";
import { registerProductionReadinessRoutes } from "../api/routes/production-readiness.js";
import { registerSecurityReadinessRoutes } from "../api/routes/security-readiness.js";
import { registerPlatformOperationsRoutes } from "../api/routes/platform-operations.js";
import { registerLaunchControlRoutes } from "../api/routes/launch-control.js";
import { registerPostLaunchMonitoringRoutes } from "../api/routes/post-launch-monitoring.js";
import { registerBusinessIntelligenceRoutes } from "../api/routes/business-intelligence.js";
import { registerExecutiveUxReadinessRoutes } from "../api/routes/executive-ux-readiness.js";
import { registerBrowserExperienceCompletenessRoutes } from "../api/routes/browser-experience-completeness.js";
import { registerOperatorSurfaceNavigationRoutes } from "../api/routes/operator-surface-navigation.js";
import { registerOperatorExperienceIntegrityRoutes } from "../api/routes/operator-experience-integrity.js";
import { registerOperatorOnboardingReadinessRoutes } from "../api/routes/operator-onboarding-readiness.js";
import { registerActionBlueprintRoutes } from "../api/routes/action-blueprint.js";
import { registerProfessionOntologyRoutes } from "../api/routes/profession-ontology.js";
import { registerProjectDecompositionRoutes } from "../api/routes/project-decomposition.js";
import { registerTekrrIntelligenceRoutes } from "../api/routes/tekrr-intelligence.js";
import { registerExecutionBlueprintRoutes } from "../api/routes/execution-blueprint.js";
import { registerBlueprintGovernanceRoutes } from "../api/routes/blueprint-governance.js";
import { registerMarketplaceCompilationRoutes } from "../api/routes/marketplace-compilation.js";
import { registerIntelligentPricingRoutes } from "../api/routes/intelligent-pricing.js";
import { registerIntelligentCommissionRoutes } from "../api/routes/intelligent-commission.js";
import { registerPersonalAssistantRoutes } from "../api/routes/personal-assistant.js";
import { registerDevelopMeRoutes } from "../api/routes/develop-me.js";
import { registerLearnByActionRoutes } from "../api/routes/learn-by-action.js";
import { registerExpertNetworkRoutes } from "../api/routes/expert-network.js";
import { registerTeamBuilderRoutes } from "../api/routes/team-builder.js";
import { registerKnowledgeBankRoutes } from "../api/routes/knowledge-bank.js";
import { registerIntelligenceOrchestrationRoutes } from "../api/routes/intelligence-orchestration.js";
import { registerActionIntelligenceRoutes } from "../api/routes/action-intelligence.js";
import { registerActionOntologyRoutes } from "../api/routes/action-ontology.js";
import { registerActionPlanningRoutes } from "../api/routes/action-planning.js";
import { registerDynamicPricingRoutes } from "../api/routes/dynamic-pricing.js";
import { registerContractIntelligenceRoutes } from "../api/routes/contract-intelligence.js";
import { registerExecutionIntelligenceRoutes } from "../api/routes/execution-intelligence.js";
import { registerOutcomeIntelligenceRoutes } from "../api/routes/outcome-intelligence.js";
import { registerTrustIntelligenceRoutes } from "../api/routes/trust-intelligence.js";
import { registerDecisionIntelligenceRoutes } from "../api/routes/decision-intelligence.js";
import { registerRecommendationIntelligenceRoutes } from "../api/routes/recommendation-intelligence.js";
import { registerInsightIntelligenceRoutes } from "../api/routes/insight-intelligence.js";
import { registerPredictionIntelligenceRoutes } from "../api/routes/prediction-intelligence.js";
import { registerStrategyIntelligenceRoutes } from "../api/routes/strategy-intelligence.js";
import { registerLearningIntelligenceRoutes } from "../api/routes/learning-intelligence.js";
import { registerOptimizationIntelligenceRoutes } from "../api/routes/optimization-intelligence.js";
import { registerEvolutionIntelligenceRoutes } from "../api/routes/evolution-intelligence.js";
import { registerOrchestrationIntelligenceRoutes } from "../api/routes/orchestration-intelligence.js";
import { registerActionIntelligenceExperienceRoutes } from "../api/routes/action-intelligence-experience.js";
import { registerIntelligenceDashboardRoutes } from "../api/routes/intelligence-dashboard.js";
import { registerExecutiveIntelligenceCenterRoutes } from "../api/routes/executive-intelligence-center.js";
import { registerActionIntelligenceCertificationRoutes } from "../api/routes/action-intelligence-certification.js";
import { registerActionIntelligenceFinalClosureRoutes } from "../api/routes/action-intelligence-final-closure.js";
import { registerAiExperienceFoundationRoutes } from "../api/routes/ai-experience-foundation.js";
import { registerAiConversationExperienceRoutes } from "../api/routes/ai-conversation-experience.js";
import { registerAiGuidanceExperienceRoutes } from "../api/routes/ai-guidance-experience.js";
import { registerAiDecisionSupportExperienceRoutes } from "../api/routes/ai-decision-support-experience.js";
import { registerAiActionPlanningExperienceRoutes } from "../api/routes/ai-action-planning-experience.js";
import { registerAiExecutionCompanionExperienceRoutes } from "../api/routes/ai-execution-companion-experience.js";
import { registerAiProgressIntelligenceExperienceRoutes } from "../api/routes/ai-progress-intelligence-experience.js";
import { registerAiAdaptiveCoachingExperienceRoutes } from "../api/routes/ai-adaptive-coaching-experience.js";
import { registerAiInsightGenerationExperienceRoutes } from "../api/routes/ai-insight-generation-experience.js";
import { registerAiRecommendationIntelligenceExperienceRoutes } from "../api/routes/ai-recommendation-intelligence-experience.js";
import { registerAiPredictiveIntelligenceExperienceRoutes } from "../api/routes/ai-predictive-intelligence-experience.js";
import { registerAiExecutiveIntelligenceExperienceRoutes } from "../api/routes/ai-executive-intelligence-experience.js";
import { registerAiOrchestrationExperienceRoutes } from "../api/routes/ai-orchestration-experience.js";
import { registerAiDecisionIntelligenceExperienceRoutes } from "../api/routes/ai-decision-intelligence-experience.js";
import { registerAiStrategicIntelligenceExperienceRoutes } from "../api/routes/ai-strategic-intelligence-experience.js";
import { registerAiPredictiveForecastExperienceRoutes } from "../api/routes/ai-predictive-forecast-experience.js";
import { registerAiExecutiveAdvisoryExperienceRoutes } from "../api/routes/ai-executive-advisory-experience.js";
import { registerAiGovernanceAssuranceExperienceRoutes } from "../api/routes/ai-governance-assurance-experience.js";
import { registerAiAccountabilityLedgerExperienceRoutes } from "../api/routes/ai-accountability-ledger-experience.js";
import { registerBrowserSurfaceRoutes } from "../api/routes/browser-surface.js";
import { registerBrowserStaticRoutes } from "../api/routes/browser-static.js";
import { registerLivingOnboardingRoutes } from "../api/routes/living-onboarding.js";
import { registerProfessionalHomeRoutes } from "../api/routes/professional-home.js";
import { registerLivingPassportRoutes } from "../api/routes/living-passport.js";
import { registerLivingLiveFrameRoutes } from "../api/routes/living-live-frame.js";
import { registerLivingJourneyRoutes } from "../api/routes/living-journey.js";
import { registerLivingTodayIActedRoutes } from "../api/routes/living-today-i-acted.js";
import { registerLivingOpportunitiesRoutes } from "../api/routes/living-opportunities.js";
import { registerLivingPartnerEcosystemRoutes } from "../api/routes/living-partner-ecosystem.js";
import { registerLivingProfessionalCommunityRoutes } from "../api/routes/living-professional-community.js";
import { registerLivingProfessionalCoachRoutes } from "../api/routes/living-professional-coach.js";
import { registerLivingActionPlannerRoutes } from "../api/routes/living-action-planner.js";
import { registerLivingProfessionalImpactRoutes } from "../api/routes/living-professional-impact.js";
import { registerLivingProfessionalIdentityRoutes } from "../api/routes/living-professional-identity.js";
import { registerLivingProfessionalIntelligenceRoutes } from "../api/routes/living-professional-intelligence.js";
import { registerLivingProfessionalSimulatorRoutes } from "../api/routes/living-professional-simulator.js";
import { registerLivingProfessionalGoalsRoutes } from "../api/routes/living-professional-goals.js";
import { registerLivingProfessionalAchievementsRoutes } from "../api/routes/living-professional-achievements.js";
import { registerLivingProfessionalAnalyticsRoutes } from "../api/routes/living-professional-analytics.js";
import { registerLivingProfessionalTimelineRoutes } from "../api/routes/living-professional-timeline.js";
import { registerLivingProfessionalCareerEngineRoutes } from "../api/routes/living-professional-career-engine.js";
import { registerNeedExperienceRoutes } from "../api/routes/need-experience.js";
import { registerActionExperienceRoutes } from "../api/routes/action-experience.js";
import { registerContractExperienceRoutes } from "../api/routes/contract-experience.js";
import { registerChatExperienceRoutes } from "../api/routes/chat-experience.js";
import { registerTimelineExperienceRoutes } from "../api/routes/timeline-experience.js";
import { registerNotificationExperienceRoutes } from "../api/routes/notification-experience.js";
import { registerProfileExperienceRoutes } from "../api/routes/profile-experience.js";
import { registerRuntimeJourneyRoutes } from "../api/routes/runtime-journey.js";
import { registerRuntimeStateRoutes } from "../api/routes/runtime-state.js";
import { registerRuntimeRegistryRoutes } from "../api/routes/runtime-registry.js";
import { registerRuntimeCoordinatorRoutes } from "../api/routes/runtime-coordinator.js";
import { registerRuntimeHealthRoutes } from "../api/routes/runtime-health.js";
import { registerRuntimeDemoRoutes } from "../api/routes/runtime-demo.js";
import { registerRuntimePreviewRoutes } from "../api/routes/runtime-preview.js";
import { registerRuntimeLauncherRoutes } from "../api/routes/runtime-launcher.js";
import { registerRuntimeReleaseRoutes } from "../api/routes/runtime-release.js";
import { registerRuntimeOperationsRoutes } from "../api/routes/runtime-operations.js";
import { registerRuntimeExecutiveRoutes } from "../api/routes/runtime-executive.js";
import { registerRuntimeReadinessRoutes } from "../api/routes/runtime-readiness.js";
import { registerRuntimeCertificationRoutes } from "../api/routes/runtime-certification.js";
import { registerRuntimeFinalReadinessRoutes } from "../api/routes/runtime-final-readiness.js";
import { registerRuntimeProductionApprovalRoutes } from "../api/routes/runtime-production-approval.js";
import { registerRuntimeOperationsCenterRoutes } from "../api/routes/runtime-operations-center.js";
import { registerRuntimeLaunchControlRoutes } from "../api/routes/runtime-launch-control.js";
import { registerRuntimeLaunchReadinessAuthorityRoutes } from "../api/routes/runtime-launch-readiness-authority.js";
import { registerRuntimeExecutiveLaunchAuthorityRoutes } from "../api/routes/runtime-executive-launch-authority.js";
import { registerRuntimeCompletionRoutes } from "../api/routes/runtime-completion.js";
import { registerPlatformExperienceRoutes } from "../api/routes/platform.js";
import type { AppDependencies } from "./dependencies.js";

export async function registerAppRoutes(
  app: FastifyInstance,
  deps: AppDependencies
): Promise<void> {
  await registerHealthRoutes(app, deps.db);
  await registerBrowserSurfaceRoutes(app, deps.browserSurface);
  await registerBrowserStaticRoutes(app, deps.browserStatic);
  await registerAuthRoutes(app, {
    auth: deps.auth,
    registration: deps.registration,
  });
  await registerSecurityAuthRoutes(app, { securityAuth: deps.securityAuth });
  await registerIdentityRoutes(app, deps.profile);
  await registerVerificationRoutes(app, deps.verification);
  await registerActionRoutes(app, deps.actions);
  await registerContractActionRoutes(app, deps.contracts);
  await registerContractRoutes(app, deps.contracts, deps.evaluation);
  await registerEvidenceRoutes(app, deps.execution);
  await registerIssueRoutes(app, deps.issues);
  await registerAiActionRoutes(app, deps.actionIntelligence);
  await registerAiRequirementRoutes(app, deps.requirementIntelligence);
  await registerAiContractRoutes(app, deps.contractIntelligence);
  await registerAiTrustRoutes(app, deps.trustIntelligence);
  await registerAiMatchingRoutes(app, deps.matchingIntelligence);
  await registerAiPricingRoutes(app, deps.pricingIntelligence);
  await registerAiNegotiationRoutes(app, deps.negotiationIntelligence);
  await registerAiWorkflowRoutes(app, deps.workflowIntelligence);
  await registerAiProviderRoutes(app, deps.providerIntelligence);
  await registerInternalContractRoutes(app, deps.contracts);
  await registerEscrowExperienceRoutes(app, deps.experience.escrow);
  await registerExecutionExperienceRoutes(app, deps.experience.execution);
  await registerEvidenceReadRoutes(app, deps.experience.evidence);
  await registerDisputesReadRoutes(app, deps.experience.dispute);
  await registerTrustExperienceRoutes(app, deps.experience.trust);
  await registerTrustReputationRoutes(app, deps.trustScore);
  await registerProviderRoutes(app, deps.providerProfile);
  await registerProviderDashboardRoutes(app, deps.providerDashboard);
  await registerRequestRoutes(app, deps.requestIntelligence);
  await registerConversionRoutes(app, deps.matchContractConversion);
  await registerCustomerDashboardRoutes(app, deps.customerDashboard);
  await registerAdminConsoleRoutes(app, deps.adminConsole);
  await registerNotificationRoutes(app, deps.eventInbox);
  await registerDiscoveryRoutes(app, deps.discovery);
  await registerAnalyticsRoutes(app, deps.platformAnalytics);
  await registerHomeRoutes(app, deps.homeExperience);
  await registerLiveFrameRoutes(app, deps.liveFrameExperience);
  await registerContractJourneyRoutes(app, deps.contractJourney);
  await registerActionEconomyRoutes(app, deps.actionEconomy);
  await registerRequestMatchRoutes(app, deps.requestMatchExperience);
  await registerEscrowPaymentRoutes(app, deps.escrowPaymentExperience);
  await registerTrustReputationExperienceRoutes(app, deps.trustReputationExperience);
  await registerDiscoveryMatchingRoutes(app, deps.discoveryMatching);
  await registerProfessionalPassportRoutes(app, deps.professionalPassport);
  await registerProfessionalSealsRoutes(app, deps.professionalSeals);
  await registerLiveTrustFrameRoutes(app, deps.liveTrustFrame);
  await registerProviderCommandCenterRoutes(app, deps.providerCommandCenter);
  await registerCustomerCommandCenterRoutes(app, deps.customerCommandCenter);
  await registerPlatformControlTowerRoutes(app, deps.platformControlTower);
  await registerMarketplaceIntelligenceRoutes(app, deps.marketplaceIntelligence);
  await registerExecutiveCommandCenterRoutes(app, deps.executiveCommandCenter);
  await registerLaunchSimulationRoutes(app, deps.launchSimulation);
  await registerInvestorReadinessRoutes(app, deps.investorReadiness);
  await registerGovernmentPartnershipRoutes(app, deps.governmentPartnership);
  await registerStrategicOperatingRoutes(app, deps.strategicOperatingSystem);
  await registerMissionControlRoutes(app, deps.missionControl);
  await registerExecutiveExperienceRoutes(app, deps.executiveExperience);
  await registerArchitectureReviewRoutes(app, deps.architectureReview);
  await registerApiAuditRoutes(app, deps.apiAudit);
  await registerProductionReadinessRoutes(app, deps.productionReadiness);
  await registerSecurityReadinessRoutes(app, deps.securityReadiness);
  await registerPlatformOperationsRoutes(app, deps.platformOperations);
  await registerLaunchControlRoutes(app, deps.launchControl);
  await registerPostLaunchMonitoringRoutes(app, deps.postLaunchMonitoring);
  await registerBusinessIntelligenceRoutes(app, deps.businessIntelligence);
  await registerExecutiveUxReadinessRoutes(app, deps.executiveUxReadiness);
  await registerBrowserExperienceCompletenessRoutes(app, deps.browserExperienceCompleteness);
  await registerOperatorSurfaceNavigationRoutes(app, deps.operatorSurfaceNavigation);
  await registerOperatorExperienceIntegrityRoutes(app, deps.operatorExperienceIntegrity);
  await registerOperatorOnboardingReadinessRoutes(app, deps.operatorOnboardingReadiness);
  await registerActionBlueprintRoutes(app, deps.actionBlueprint);
  await registerProfessionOntologyRoutes(app, deps.professionOntology);
  await registerProjectDecompositionRoutes(app, deps.projectDecomposition);
  await registerTekrrIntelligenceRoutes(app, deps.tekrrIntelligence);
  await registerExecutionBlueprintRoutes(app, deps.executionBlueprint);
  await registerBlueprintGovernanceRoutes(app, deps.blueprintGovernance);
  await registerMarketplaceCompilationRoutes(app, deps.marketplaceCompilation);
  await registerIntelligentPricingRoutes(app, deps.intelligentPricing);
  await registerIntelligentCommissionRoutes(app, deps.intelligentCommission);
  await registerPersonalAssistantRoutes(app, deps.personalAssistant);
  await registerDevelopMeRoutes(app, deps.developMe);
  await registerLearnByActionRoutes(app, deps.learnByAction);
  await registerExpertNetworkRoutes(app, deps.expertNetwork);
  await registerTeamBuilderRoutes(app, deps.teamBuilder);
  await registerKnowledgeBankRoutes(app, deps.knowledgeBank);
  await registerIntelligenceOrchestrationRoutes(app, deps.intelligenceOrchestration);
  await registerActionIntelligenceRoutes(app, deps.unifiedActionIntelligence);
  await registerActionOntologyRoutes(app, deps.actionOntology);
  await registerActionPlanningRoutes(app, deps.actionPlanning);
  await registerDynamicPricingRoutes(app, deps.dynamicPricing);
  await registerContractIntelligenceRoutes(app, deps.contractIntelligenceEngine);
  await registerExecutionIntelligenceRoutes(app, deps.executionIntelligenceEngine);
  await registerOutcomeIntelligenceRoutes(app, deps.outcomeIntelligenceEngine);
  await registerTrustIntelligenceRoutes(app, deps.trustIntelligenceEngine);
  await registerDecisionIntelligenceRoutes(app, deps.decisionIntelligenceEngine);
  await registerRecommendationIntelligenceRoutes(app, deps.recommendationIntelligenceEngine);
  await registerInsightIntelligenceRoutes(app, deps.insightIntelligenceEngine);
  await registerPredictionIntelligenceRoutes(app, deps.predictionIntelligenceEngine);
  await registerStrategyIntelligenceRoutes(app, deps.strategyIntelligenceEngine);
  await registerLearningIntelligenceRoutes(app, deps.learningIntelligenceEngine);
  await registerOptimizationIntelligenceRoutes(app, deps.optimizationIntelligenceEngine);
  await registerEvolutionIntelligenceRoutes(app, deps.evolutionIntelligenceEngine);
  await registerOrchestrationIntelligenceRoutes(app, deps.orchestrationIntelligenceEngine);
  await registerActionIntelligenceExperienceRoutes(app, deps.actionIntelligenceExperience);
  await registerIntelligenceDashboardRoutes(app, deps.intelligenceDashboard);
  await registerExecutiveIntelligenceCenterRoutes(app, deps.executiveIntelligenceCenter);
  await registerActionIntelligenceCertificationRoutes(app, deps.actionIntelligenceCertification);
  await registerActionIntelligenceFinalClosureRoutes(app, deps.actionIntelligenceFinalClosure);
  await registerAiExperienceFoundationRoutes(app, deps.aiExperienceFoundation);
  await registerAiConversationExperienceRoutes(app, deps.aiConversationExperience);
  await registerAiGuidanceExperienceRoutes(app, deps.aiGuidanceExperience);
  await registerAiDecisionSupportExperienceRoutes(app, deps.aiDecisionSupportExperience);
  await registerAiActionPlanningExperienceRoutes(app, deps.aiActionPlanningExperience);
  await registerAiExecutionCompanionExperienceRoutes(app, deps.aiExecutionCompanionExperience);
  await registerAiProgressIntelligenceExperienceRoutes(app, deps.aiProgressIntelligenceExperience);
  await registerAiAdaptiveCoachingExperienceRoutes(app, deps.aiAdaptiveCoachingExperience);
  await registerAiInsightGenerationExperienceRoutes(app, deps.aiInsightGenerationExperience);
  await registerAiRecommendationIntelligenceExperienceRoutes(
    app,
    deps.aiRecommendationIntelligenceExperience
  );
  await registerAiPredictiveIntelligenceExperienceRoutes(
    app,
    deps.aiPredictiveIntelligenceExperience
  );
  await registerAiExecutiveIntelligenceExperienceRoutes(
    app,
    deps.aiExecutiveIntelligenceExperience
  );
  await registerAiOrchestrationExperienceRoutes(app, deps.aiOrchestrationExperience);
  await registerAiDecisionIntelligenceExperienceRoutes(
    app,
    deps.aiDecisionIntelligenceExperience
  );
  await registerAiStrategicIntelligenceExperienceRoutes(
    app,
    deps.aiStrategicIntelligenceExperience
  );
  await registerAiPredictiveForecastExperienceRoutes(app, deps.aiPredictiveForecastExperience);
  await registerAiExecutiveAdvisoryExperienceRoutes(app, deps.aiExecutiveAdvisoryExperience);
  await registerAiGovernanceAssuranceExperienceRoutes(app, deps.aiGovernanceAssuranceExperience);
  await registerAiAccountabilityLedgerExperienceRoutes(app, deps.aiAccountabilityLedgerExperience);
  await registerLivingOnboardingRoutes(app, deps.livingOnboarding);
  await registerProfessionalHomeRoutes(app, deps.professionalHome);
  await registerLivingPassportRoutes(app, deps.livingPassport);
  await registerLivingLiveFrameRoutes(app, deps.livingLiveFrame);
  await registerLivingJourneyRoutes(app, deps.livingJourney);
  await registerLivingTodayIActedRoutes(app, deps.livingTodayIActed);
  await registerLivingOpportunitiesRoutes(app, deps.livingOpportunities);
  await registerLivingPartnerEcosystemRoutes(app, deps.livingPartnerEcosystem);
  await registerLivingProfessionalCommunityRoutes(app, deps.livingProfessionalCommunity);
  await registerLivingProfessionalCoachRoutes(app, deps.livingProfessionalCoach);
  await registerLivingActionPlannerRoutes(app, deps.livingActionPlanner);
  await registerLivingProfessionalImpactRoutes(app, deps.livingProfessionalImpact);
  await registerLivingProfessionalIdentityRoutes(app, deps.livingProfessionalIdentity);
  await registerLivingProfessionalIntelligenceRoutes(app, deps.livingProfessionalIntelligence);
  await registerLivingProfessionalSimulatorRoutes(app, deps.livingProfessionalSimulator);
  await registerLivingProfessionalGoalsRoutes(app, deps.livingProfessionalGoals);
  await registerLivingProfessionalAchievementsRoutes(app, deps.livingProfessionalAchievements);
  await registerLivingProfessionalAnalyticsRoutes(app, deps.livingProfessionalAnalytics);
  await registerLivingProfessionalTimelineRoutes(app, deps.livingProfessionalTimeline);
  await registerLivingProfessionalCareerEngineRoutes(app, deps.livingProfessionalCareerEngine);
  await registerNeedExperienceRoutes(app, deps.needExperience);
  await registerActionExperienceRoutes(app, deps.actionExperience);
  await registerContractExperienceRoutes(app, deps.contractExperience);
  await registerChatExperienceRoutes(app, deps.chatExperience);
  await registerTimelineExperienceRoutes(app, deps.timelineExperience);
  await registerNotificationExperienceRoutes(app, deps.notificationExperience);
  await registerProfileExperienceRoutes(app, deps.profileExperience);
  await registerRuntimeJourneyRoutes(app, deps.runtimeJourney);
  await registerRuntimeStateRoutes(app, deps.runtimeState);
  await registerRuntimeRegistryRoutes(app, deps.runtimeRegistry);
  await registerRuntimeCoordinatorRoutes(app, deps.runtimeCoordinator);
  await registerRuntimeHealthRoutes(app, deps.runtimeHealth);
  await registerRuntimeDemoRoutes(app, deps.runtimeDemo);
  await registerRuntimePreviewRoutes(app, deps.runtimePreview);
  await registerRuntimeLauncherRoutes(app, deps.runtimeLauncher);
  await registerRuntimeReleaseRoutes(app, deps.runtimeRelease);
  await registerRuntimeOperationsRoutes(app, deps.runtimeOperations);
  await registerRuntimeExecutiveRoutes(app, deps.runtimeExecutive);
  await registerRuntimeReadinessRoutes(app, deps.runtimeReadiness);
  await registerRuntimeCertificationRoutes(app, deps.runtimeCertification);
  await registerRuntimeFinalReadinessRoutes(app, deps.runtimeFinalReadiness);
  await registerRuntimeProductionApprovalRoutes(app, deps.runtimeProductionApproval);
  await registerRuntimeOperationsCenterRoutes(app, deps.runtimeOperationsCenter);
  await registerRuntimeLaunchControlRoutes(app, deps.runtimeLaunchControl);
  await registerRuntimeLaunchReadinessAuthorityRoutes(app, deps.runtimeLaunchReadinessAuthority);
  await registerRuntimeExecutiveLaunchAuthorityRoutes(app, deps.runtimeExecutiveLaunchAuthority);
  await registerRuntimeCompletionRoutes(app, deps.runtimeCompletion);
  await registerReleaseReadinessRoutes(app, deps.releaseReadinessCenter);
  await registerPlatformExperienceRoutes(app, deps.experience.platform);
}
